- name: nginx folder
  file:
    path: "/home/vagrant/nginx"
    state: directory
    mode: 744
    owner: vagrant
    group: vagrant

- name: nginx config
  copy:
    src: nginx.conf
    dest: "/home/vagrant/nginx/nginx.conf"
    mode: '0644'
    owner: vagrant
    group: vagrant

- name: Install pip3
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install docker module
  ansible.builtin.pip:
    name: docker

- name: Run Nginx
  community.docker.docker_container:
    name: nginx
    image: docker.io/library/nginx:1.23.3-alpine
    state: started
    recreate: yes
    privileged: yes
    network_mode: host
    volumes:
      - /home/vagrant/nginx/nginx.conf:/etc/nginx/nginx.conf:ro