- name: traefik folder
  file:
    path: "/home/vagrant/traefik"
    state: directory
    mode: 744
    owner: vagrant
    group: vagrant

- name: traefik config
  copy:
    src: traefik.yml
    dest: "/home/vagrant/traefik/traefik.yml"
    mode: '0644'
    owner: vagrant
    group: vagrant

- name: Install pip3
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install docker module
  ansible.builtin.pip:
    name: docker

- name: Run HAProxy
  community.docker.docker_container:
    name: haproxy
    image: docker.io/library/traefik:v1.7.34-alpine
    state: started
    recreate: yes
    privileged: yes
    network_mode: host
    volumes:
      - /home/vagrant/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
