- name: Configure LoadBalancer
  hosts: loadbalancer
  become: true
  connection: local
  tasks:
  - name: docker
    include_role:
      name: geerlingguy.docker
    vars:
      docker_users:
        - vagrant
        
  - name: nginx
    include_role:
      name: nginx
